name: Publish to NPM

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0, v1.0.1, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed

            This release includes:
            - React components for country code selection with flags
            - Support for both emoji flags and image flags
            - TypeScript support with full type definitions
            - Comprehensive documentation and examples

            ## Installation

            ```bash
            npm install react-phone-flag
            ```

            ## Usage

            ```jsx
            import { CountryCodeSelector, PhoneFlagSelector } from 'react-phone-flag';

            // Basic usage
            <CountryCodeSelector 
              value="US" 
              onChange={(country) => console.log(country)} 
            />

            // With phone input
            <PhoneFlagSelector 
              value="+1234567890" 
              onChange={(phone, country) => console.log(phone, country)} 
            />
            ```
          draft: false
          prerelease: false
